name: ci 
on:
  push:
    branches:
      - main  # or master, depending on your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-glightbox 'mkdocs[i18n]' mkdocs-get-deps mkdocs-material-extensions
          pip list
      - name: Debug Info
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -R
      - name: Build MkDocs
        run: |
          cd docs
          mkdocs build --verbose
          echo "Build directory contents:"
          ls -R site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mkdocs/site
          force_orphan: true
      - name: Check deployment
        run: |
          echo "Checking gh-pages branch"
          git checkout gh-pages
          ls -R